layout_spectrum: 0
typography_spectrum: 0.287234
color:
  saturation: 0.8851416
  lightness: 0.5631325
  brandStrength: 0.9617021
  brandColors:
    - '#160E0C'
    - '#1F304B'
    - '#FDFDFC'
    - '#E0CE9A'
    - '#5D5342'
  rhythmicContrast: 0.6170213
name: Reinold Consultants
